--  category:  IBM i サービス応用
--  description:  WRKOBJOWN類似
SELECT a.*,
       CAST(CAST(TEXT_DESCRIPTION AS CHAR(50) CCSID 65535) AS CHAR(50) CCSID 1399) AS DBCS_DESC
  FROM QSYS2.OBJECT_OWNERSHIP AS a
  WHERE AUTHORIZATION_NAME = 'QPGMR'
        AND PATH_NAME IS NULL;