--  category:  IBM i サービス応用
--  description: サーバー間のシステム値の比較
DISCONNECT ALL;
-- CONNECT TO ローカル・データベース名  USER ユーザーID USING 'パスワード';
CONNECT TO リモート・データベース名1 USER ユーザーID USING 'パスワード';
CONNECT TO リモート・データベース名2 USER ユーザーID USING 'パスワード';

DECLARE GLOBAL TEMPORARY TABLE SESSION.SYSVAL_L1 AS
            (SELECT *
                    FROM QSYS2.SYSTEM_VALUE_INFO
                    ORDER BY SYSTEM_VALUE_NAME)
            WITH DATA INCLUDING DEFAULTS
    WITH REPLACE;
DECLARE GLOBAL TEMPORARY TABLE SESSION.SYSVAL_L2 AS
            (SELECT *
                    FROM LPAR72A.QSYS2.SYSTEM_VALUE_INFO
                    ORDER BY SYSTEM_VALUE_NAME)
            WITH DATA INCLUDING DEFAULTS
    WITH REPLACE;
DECLARE GLOBAL TEMPORARY TABLE SESSION.SYSVAL_L3 AS
            (SELECT *
                    FROM LPAR73A.QSYS2.SYSTEM_VALUE_INFO
                    ORDER BY SYSTEM_VALUE_NAME)
            WITH DATA INCLUDING DEFAULTS
    WITH REPLACE;
SELECT a.SYSTEM_VALUE_NAME AS SYSVAL_NAME,
       IFNULL(a.CURRENT_CHARACTER_VALUE, CHAR(a.CURRENT_NUMERIC_VALUE)) L1_VALUE,
       IFNULL(b.CURRENT_CHARACTER_VALUE, CHAR(b.CURRENT_NUMERIC_VALUE)) L2_VALUE,
       CASE
           WHEN a.CURRENT_NUMERIC_VALUE <> b.CURRENT_NUMERIC_VALUE THEN 1
           WHEN a.CURRENT_CHARACTER_VALUE <> b.CURRENT_CHARACTER_VALUE THEN 2
           ELSE 0
       END AS L2_DIFF,
       IFNULL(c.CURRENT_CHARACTER_VALUE, CHAR(c.CURRENT_NUMERIC_VALUE)) L3_VALUE,
       CASE
           WHEN a.CURRENT_NUMERIC_VALUE <> c.CURRENT_NUMERIC_VALUE THEN 1
           WHEN a.CURRENT_CHARACTER_VALUE <> c.CURRENT_CHARACTER_VALUE THEN 2
           ELSE 0
       END AS L3_DIFF
    FROM SESSION.SYSVAL_L1 AS a
         FULL OUTER JOIN SESSION.SYSVAL_L2 AS b
             ON a.SYSTEM_VALUE_NAME = b.SYSTEM_VALUE_NAME
         FULL OUTER JOIN SESSION.SYSVAL_L3 AS c
             ON a.SYSTEM_VALUE_NAME = c.SYSTEM_VALUE_NAME;